import React from 'react'
import { ThemeProvider } from '@/providers/ThemeProvider'

import './index.scss'

const baseClass = 'multi-tenant'

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
}

// eslint-disable-next-line no-restricted-exports
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={baseClass} lang="fr" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
